### ISSUE TITLE
can nlcst-parse-japanese work in the browser?

### ISSUE THREAD

**Issue by linonetwo** [azu/nlp-pattern-match#5]
Seems it always loads failed.
```error
Error: invalid file signature:60,33          gunzip.min.js:652

    g gunzip.min.js:652
    onload BrowserDictionaryLoader.js:52 
```
And example don't even work in the [runkit](https://npm.runkit.com/nlcst-parse-japanese):
```js
const { JapaneseParser } = require('nlcst-parse-japanese')
const japaneseParse = new JapaneseParser();
const text = "ようこそ、日本へ。";
japaneseParse.ready().then(() => {
    const CST = japaneseParse.parse(text);
    console.log(CST)
});
// Promise {}
```
It quits with empty promise.
And 
```js
const { JapaneseParser } = require('nlcst-parse-japanese')
const japaneseParse = new JapaneseParser();
const text = "ようこそ、日本へ。";
await japaneseParse.ready();
const CST = japaneseParse.parse(text);
console.log(CST)
```
Exited unexpectedly with code: 137

**Comment by linonetwo** [comment]
How ever it works on stackblitz? https://stackblitz.com/edit/react-iv2t8n

But just don't work on local CRA 2.0

**Comment by linonetwo** [comment]
Oh, I know. In stackblitz, gzip was loaded from `https://react-iv2t8n.stackblitz.io/turbo_modules/kuromoji@0.1.1/dict/unk_compat.dat.gz`, with correct Content-Type.

But in local development Create-React-App project,
it tried to load gzip from `http://localhost:3000/node_modules/kuromoji/dict/base.dat.gz` (and in deployment enviromnent `http://localhost:5000/dict/base.dat.gz` which is acceptable)
Which is not served by the development server, and instead it returns an index.html, so there is an `invalid file signature`.

I don't know whether I can dealwith it on my side.

Can you pass `dicPath` config down to `kuromojin` so we can have custom dict path, for example `/static/dict/xxx`?

**Comment by linonetwo** [comment]
Oh, I see https://github.com/azu/kuromojin/blob/master/src/kuromojin.js#L15

So I can do:
```js
window.kuromojin = { dicPath: '/dict' };
japaneseParse.ready().then(() => {
  const CST = japaneseParse.parse(text);
  console.log(CST)
});
```
And change `package.json`
```json
    "copy-dict": "cp -R node_modules/kuromoji/dict/ public/dict/",
    "start": "npm run copy-dict && react-scripts start",
```

**Comment by azu** [comment]
Thanks for report and describe details.

> window.kuromojin = { dicPath: '/dict' };

Yes. I put this option for a workaround.

I'm ok that we add `dictPath` option to `JapaneseParser` constructor.
If you want to get it, welcome to pull request 👍 

```js
new JapaneseParser({ dictPath })
```
