### ISSUE TITLE
Do I need to build dependency tree from POS tag?

### ISSUE THREAD

**Issue by linonetwo** [azu/nlp-pattern-match#8]
In `nlcst-parse-japanese`, you seem to get a tree out of a POS tag array.

Is that CST a dependency tree? Or just a simple CST representing paragraph-sentence structure?

I'd like to add a `nlcst-parse-chinese`, I'm considering whether I need to build a dependency tree for it.

**Comment by azu** [comment]
`nlcst-parse-japanese` is just a fork of [muraken720/parse-japanese](https://github.com/muraken720/parse-japanese) and modify API.
So, I'm not original author, but `nlcst-parse-japanese` is not Dependency Structure Analyzer.
It just tokenize japanese text to morpheme.
([kuromoji.js](https://github.com/takuyaa/kuromoji.js) is Morphological Analyzer, it is not Dependency Structure Analyzer)

This CST does not represent the dependency between each words.

**Comment by linonetwo** [comment]
OK, now it's easy, I can just fork `nlcst-parse-japanese` and modify it to adopt a Chinese POS tagger, I think they are basically the same.

Seems a simple CST is enough for powerful pattern matching.
